### ISSUE TITLE
Updated URL regexes for wezterm

### ISSUE THREAD

**Issue by pragma-** [yashpalgoyal1304/yafc#1]
https://github.com/pragma-/dotfiles/blob/c6c9498f53f812ea872fdf94e044f63956862756/wezterm/wezterm.lua#L70-L85

I wasn't sure how to contact you outside of the mintty issue. Opening an issue on one of your empty repos seemed like a way to reach you without using e-mail or adding more noise to the mintty issue.

Anyway, I updated my regexes to be a bit more robust. They now properly handle URLs that are nested within punctuation characters and they now properly include trailing ), /, or -. Just thought I'd ping you and let you know in case this affects you.

https://github.com/wez/wezterm/issues/3112

edit: uh oh, it seems that linking to the wezterm issue put a mention on that issue. Whoops.

**Comment by pragma-** [comment]
https://github.com/wez/wezterm/issues/3112

**Comment by yashpalgoyal1304** [comment]
i am wondering how did u pick out this repo for posting issue? 😅 

as i have lots of repos, so, how did u single down on this? 😃

**Comment by pragma-** [comment]
The repo was empty and had a very short ambiguous name. 😃

**Comment by yashpalgoyal1304** [comment]
haha

**Comment by goyalyashpal** [comment]
hey @pragma- 

This repo's purpose has been fulfilled. And i have to delete this repo now.

So, please backup the input you gave here and ping me when done 😃.
I will wait for 10-15 days at max.

**Comment by goyalyashpal** [comment]
> The repo was empty and had a very short ambiguous name. 😃

Oh! also, the small umh, suspense buster - this repo was intended to contain the migration of the `yafc` software, which stood for "Yet another FTP client". 

More details if u are curious here: https://github.com/msys2/MSYS2-packages/discussions/3534#discussioncomment-4874152

And why "this repo's purpose has been fulfilled" is also mentioned there itself in new comment i made today.

**Comment by goyalyashpal** [comment]
> I will wait for 10-15 days at max.
> \- 2023.03.07

oh lol, see how delay i make in things at times lol. it's past 2024.07.21 even, and it's still around here lol.
